#!/bin/bash
CDIR=$PWD

cd /tmp/$USER
git clone --mirror git@github.com:cms-sw/cmssw cmssw.git

cd $CDIR

cmsrel CMSSW_5_3_11
cd CMSSW_5_3_11/src
cmsenv

git init 
git remote add setup git@github.com:h2gglobe/setup
git fetch setup
git merge setup/master
#git checkout TAG
git submodule init 
git submodule update

git remote add cmssw_local /tmp/$USER/cmssw.git

#need to fetch at each checkout -> Local mirror
#addpkg CommonTools/RecoUtils V00-00-09 771a64690052e4b4e7eaf68d41f19ba03c6ea05e
git fetch cmssw_local CMSSW_6_2_X
git checkout 771a64690052e4b4e7eaf68d41f19ba03c6ea05e -- CommonTools/RecoUtils

#addpkg RecoEgamma/EgammaTools V09-00-00 ae6aebfd02089494ec045953f1a13c6719d8f9d6
git fetch cmssw_local CMSSW_6_2_X
git checkoout ae6aebfd02089494ec045953f1a13c6719d8f9d6 -- RecoEgamma/EgammaTools

cp HiggsAnalysis/HiggsTo2photons/scripts/download.url EGamma/EGammaAnalysisTools/data/.
cd EGamma/EGammaAnalysisTools/data/
wget -i ../../../HiggsAnalysis/HiggsTo2photons/scripts/download.url
cd ../../../

##################### UNUSED STUFF & USEFUL COMMAND
#echo "CommonTools/RecoUtils" >> .git/info/sparsecheckout
#echo "RecoEgamma/EgammaTools" >> .git/info/sparsecheckout
#git addpkg CommonTools/RecoUtils
#git addpkg RecoEgamma/EgammaTools
#git rev-list -n 1 --before="=2013-05-23 15:41:36" CMSSW_6_2_X

#git remote add cmssw git@github.com:cms-sw/cmssw
#git fetch cmssw-main-ro
